### PR TITLE
impl display for logicalplan

### PR DESCRIPTION
**Pull request by GanZiheng**
Signed-off-by: GanZiheng <ganziheng98@gmail.com>

### CODE REVIEW

**Comment by Veeupup** [comment]
try `make lint` before push

**Comment by Veeupup** [comment]
I have tried it locally, seems amazing, how about eating MaLaXiangGuo at 18:00? @GanZiheng

**Comment by GanZiheng** [comment]
> I have tried it locally, seems amazing, how about eating MaLaXiangGuo at 18:00? @GanZiheng

No problem!

**Comment by Veeupup** [comment]
image
maybe we can avoid print source table data in logical plan.
This is when I add a line in `db.rs`
```rust
impl NaiveDB {
    pub fn run_sql(&self, sql: &str) -> Result<Vec<RecordBatch>> {
       ...
        // 3. optimize
        let optimizer = Optimizer::default();
        let logical_plan = optimizer.optimize(logical_plan);
        println!("{}", logical_plan);
...
    }
```

**Pull request merged**
